// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ARP.ONE.Generation.Models;

[Table("category")]
public partial class Category
{
    [Key]
    [Column("category_id", TypeName = "SMALLINT")]
    public short CategoryId { get; set; }

    [Required]
    [Column("name", TypeName = "VARCHAR(25)")]
    public string Name { get; set; }

    [Column("last_update", TypeName = "TIMESTAMP")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<FilmCategory> FilmCategories { get; set; } = new List<FilmCategory>();
}