// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ARP.ONE.Generation.Models;

[PrimaryKey("ActorId", "FilmId")]
[Table("film_actor")]
[Index("ActorId", Name = "idx_fk_film_actor_actor")]
[Index("FilmId", Name = "idx_fk_film_actor_film")]
public partial class FilmActor
{
    [Key]
    [Column("actor_id", TypeName = "INT")]
    public int ActorId { get; set; }

    [Key]
    [Column("film_id", TypeName = "INT")]
    public int FilmId { get; set; }

    [Column("last_update", TypeName = "TIMESTAMP")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("ActorId")]
    [InverseProperty("FilmActors")]
    public virtual Actor Actor { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("FilmActors")]
    public virtual Film Film { get; set; }
}