// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ARP.ONE.Generation.Models;

[Keyless]
public partial class SalesByFilmCategory
{
    [Column("category", TypeName = "VARCHAR(25)")]
    public string Category { get; set; }

    [Column("total_sales")]
    public double? TotalSales { get; set; }
}