// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ARP.ONE.Generation.Models;

[Keyless]
public partial class StaffList
{
    [Column("ID", TypeName = "SMALLINT")]
    public short? Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("address", TypeName = "VARCHAR(50)")]
    public string Address { get; set; }

    [Column("zip_code", TypeName = "VARCHAR(10)")]
    public string ZipCode { get; set; }

    [Column("phone", TypeName = "VARCHAR(20)")]
    public string Phone { get; set; }

    [Column("city", TypeName = "VARCHAR(50)")]
    public string City { get; set; }

    [Column("country", TypeName = "VARCHAR(50)")]
    public string Country { get; set; }

    [Column("SID", TypeName = "INT")]
    public int? Sid { get; set; }
}