// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ARP.ONE.Generation.Models;

[Table("staff")]
[Index("AddressId", Name = "idx_fk_staff_address_id")]
[Index("StoreId", Name = "idx_fk_staff_store_id")]
public partial class Staff
{
    [Key]
    [Column("staff_id", TypeName = "SMALLINT")]
    public short StaffId { get; set; }

    [Required]
    [Column("first_name", TypeName = "VARCHAR(45)")]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name", TypeName = "VARCHAR(45)")]
    public string LastName { get; set; }

    [Column("address_id", TypeName = "INT")]
    public int AddressId { get; set; }

    [Column("picture")]
    public byte[] Picture { get; set; }

    [Column("email", TypeName = "VARCHAR(50)")]
    public string Email { get; set; }

    [Column("store_id", TypeName = "INT")]
    public int StoreId { get; set; }

    [Column("active", TypeName = "SMALLINT")]
    public short Active { get; set; }

    [Required]
    [Column("username", TypeName = "VARCHAR(16)")]
    public string Username { get; set; }

    [Column("password", TypeName = "VARCHAR(40)")]
    public string Password { get; set; }

    [Column("last_update", TypeName = "TIMESTAMP")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Staff")]
    public virtual Address Address { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Staff")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    [ForeignKey("StoreId")]
    [InverseProperty("Staff")]
    public virtual Store Store { get; set; }

    [InverseProperty("ManagerStaff")]
    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}