<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MudBlazor.ThemeManager" Version="3.0.0" />
    <ProjectReference Include="..\ARP.ONE.BlazorApp.Client\ARP.ONE.BlazorApp.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.*" />
  </ItemGroup>

</Project>